### ISSUE TITLE
Push Latest Versions to Packagist?

### ISSUE THREAD

**Issue by jenn-mitchell** [star7th/showdoc#1661]
Hello, will you be making the latest version available on Packagist? The latest available release on Packagist is 2.10.3.

Thanks!

**Comment by star7th** [comment]
It has been set up before to automatically push the latest. Now I don't know why the mechanism has been changed. What I think is that because showdoc is not a composer component, it is a relatively independent product, so composer installation is not the best way. The official recommended practice now is: non PHP developers use docker to install, and PHP developers directly install git clone or download code. The composer installation will not be maintained.
