### ISSUE TITLE
Proposal: Premium/Payment for rights

### ISSUE THREAD

**Issue by svliantiss** [star7th/showdoc#473]
Premium or Payment option to remove the logo and refrences to ShowDoc.

Clients of ours want to use this as well but they don't want to advertise for ShowDoc.

**Comment by star7th** [comment]
This involves some business model considerations.
I want to do open source software as well as online document hosting service mainly for Chinese users. The local market in China will be the possible way for showdoc to commercialize in the future. But it may not necessarily be commercialized, or it may be just a simple public service. It mainly depends on the scale of future users and the willingness of enterprises to pay.
In the foreign market, I don't intend to make a profit because of the small number of users and the troublesome way of collecting money. It's all about providing open source tools with a helpful mentality. So I may not have the motivation to offer other premium versions. But I don't mind you removing showdoc links technically. Just do it ， there's no psychological burden.

**Comment by star7th** [comment]
By online document hosting service for Chinese users, I mean the website https://www.showdoc.cc/ . Now there are quite a few small and medium-sized enterprises in China.

**Comment by svliantiss** [comment]
You could keep everything the same just allow users to purchase a License which allows them to remove all ShowDoc branding.

**Comment by star7th** [comment]
You can just remove all ShowDoc branding on your own version  and  I'm not going to pursue your legal or other responsibilities.  I think very few people have this need. So I don't want to have trouble collecting money and registering enterprise  for this.

**Comment by svliantiss** [comment]
I personally don't care for the branding it's just clients of ours don't want it. And they I cannot advise them or give them the green light to do it if there is a legal issue at hand. I just see a win-win situation for everyone. They can legally remove the branding they don't want and you earn money of your fantastic application.
